########################################################################################

# This Makefile generated by GoMakeGen 0.6.0 using next command:
# gomakegen .

########################################################################################

.PHONY = fmt all clean deps

########################################################################################

all: piper

piper:
	go build piper.go

deps:
	git config --global http.https://pkg.re.followRedirects true
	go get -u pkg.re/essentialkaos/ek.v9
	go get -u github.com/djherbis/times

fmt:
	find . -name "*.go" -exec gofmt -s -w {} \;

clean:
	rm -f piper

########################################################################################
